services:
  backend:
    build: ./backend
    ports:
      - 5000:5000 
    volumes:
        
      - ./backend/src:/app/src
    
  db:
    image: postgres
    ports:
      - 5433:5432 
    volumes:
      - /var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: thegoodcorner 
   # frontend:
  #   build: ./frontend
  #   command: npm run dev
  #   ports:
  #     - 3001:3000 
  #   volumes:
  #     - ./frontend/src:/app/src